### ISSUE TITLE
"Please redownload the plugin to install the new version"

### ISSUE THREAD

**Issue by Naemy** [einancunlu/Disconnect-for-Sketch#2]
I've downloaded the plugin via Sketch Toolbox. When I try to use it via Plugins, I get the message : 

"There is a new version of the plugin!
Please redownload the plugin to install the new version."

Tried uninstalling and re-downloading it a few times, still the same issue.
My current Sketch version : 3.4.4 
Your plugin looks great, I'd love to be able to use it ^_^

**Comment by einancunlu** [comment]
I found the bug and fixed it with an update, sorry for the inconvenience... I wasn't getting this false update warning somehow, and so I didn't realize it. Thanks for letting me know! : )

**Comment by Naemy** [comment]
Thanks for the fix! :)

**Comment by einancunlu** [comment]
You're welcome! Do you have any nice plugin idea? I like to ask that question to random people, something good can come out and I would love to be part of it. : )

**Comment by Naemy** [comment]
I've never coded a plugin for Sketch so I'm not sure of the limitations of it, but I know I'd be interested in a plugin to handle Symbols or Text Styles in a better way (especially Text Styles). Maybe a way to handle Global Colors and change colors globally (in both symbols and texts). 

These are my ideas :)

**Comment by einancunlu** [comment]
You can think it like mostly it has the same limitations as your ability to manipulate the items. Real problem here is that we're not able to change UI elements of the Sketch app or add additional functionality into the UI except by doing some tricks. (one of the plugins managed to add an icon into the toolbar, but this is not officially supported.) And also as I know, it's hard to have the plugin running synchronously while you're using Sketch.

Oh actually I want the global colors so much too, I mean something works like symbols. If we could create color variables and change them easily, it would be so helpful. There is a way of doing this partially with [this plugin](https://github.com/JohnCoates/CSSketch), but it's not as easy as it seems. I tried sometime and stop using because of some bugs and limitations. 

I was thinking to make a plugin that allows to change colors in a group easily. I generally need to change colors of vectors or shapes in an icon for a lot of times. So for me it's hard to select every elements in the group and change colors one by one. (Because border and fill color can be separate it's hard to change all by selecting them all.)

Thanks for the thoughts. I liked your website by the way, you have a good ability to write things sincerely. : )
